title: Cybersecurity Education and Research Center
description: University of Wyoming's Cybersecurity Education and Research Center

google_analytics:
theme: cedar-theme

contact:
  name: Dr. Mike Borowczak
  position: CEDAR Director
  room: EN 4071B
  dept: Dept. 3315
  street: 1000 E. University Ave.
  addr: Laramie, WY 82071
  email: cedar@cs.uwyo.edu
